/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Carregando.java
 *
 * Created on Feb 1, 2012, 6:59:57 PM
 */

package GUI;

import java.awt.Graphics;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author diogo
 */
public class Carregando extends javax.swing.JFrame {


	// <editor-fold defaultstate="collapsed" desc="Singleton">
	private static Carregando instance;

	public static Carregando GetInsance() {
		return instance;
	}
	// </editor-fold>

	/**
	 * Mostra tela de carregar
	 */
	public static void Mostrar(){
		if (GetInsance() == null) {
			Carregando c = new Carregando();
			
			Carregando.instance = c;
		}
		
		Carregando.instance.setLocationRelativeTo(null);
		Carregando.instance.setVisible(true);
	}

	/**
	 * Oculta/Fecha a tela de carregar
	 */
	public static void Ocultar() {
		if (GetInsance() != null) {
			GetInsance().setVisible(false);
		}
	}

    /** Creates new form Carregando */
    public Carregando() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        M = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        M.setBackground(new java.awt.Color(255, 255, 255));
        M.setFont(new java.awt.Font("Comic Sans MS", 1, 43)); // NOI18N
        M.setForeground(new java.awt.Color(255, 0, 0));
        M.setText("Carregando...");
        M.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        M.setOpaque(true);
        M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MMouseExited(evt);
            }
        });
        M.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(M)
                    .addGap(0, 79, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 19, Short.MAX_VALUE)
                    .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void MMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseClicked

}//GEN-LAST:event_MMouseClicked

	private void MMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseExited
		M.setBackground(new java.awt.Color(255, 255, 255));
}//GEN-LAST:event_MMouseExited

	private void MMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseMoved
		M.setBackground(new java.awt.Color(255, 255, 133));
}//GEN-LAST:event_MMouseMoved

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
				Carregando c = new Carregando();
                c.setVisible(true);
				Carregando.instance = c;
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel M;
    // End of variables declaration//GEN-END:variables

}
